name: Wavepacket CI
run-name: Testing ${{ github.ref_name }} with ref ${{ github.ref }}

on:
  push

jobs:
  Run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: cp313
        with:
          python-version: '3.13'
      - run: ${{ steps.cp313.outputs.python-path }} -m venv ~/venv
      - run: ~/venv/bin/python -m pip install flit
      - run: cd $GITHUB_WORKSPACE && ~/venv/bin/flit install --deps all
      - run: ~/venv/bin/pytest $GITHUB_WORKSPACE/test
